{{- if .Values.cloudsqlproxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ template "mysql-exporter.cloudsqlsecret" . }}
  labels:
    {{- include "mysql-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.cloudsqlproxy.credentials | b64enc }}
{{- end }}
