apiVersion: v2
name: beehive
description: ExporterHub Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.0.0
annotations:
  modified_by: nexclipper
dependencies:
- condition: prometheus-adapter.enabled
  name: prometheus-adapter
  repository: https://prometheus-community.github.io/helm-charts
  version: 2.14.2
- condition: prometheus-blackbox-exporter.enabled
  name: blackbox-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.14.0
- condition: prometheus-cloudwatch-exporter.enabled
  name: cloudwatch-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 0.16.0
- condition: prometheus-consul-exporter.enabled
  name: consul-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 0.4.0
- condition: prometheus-elasticsearch-exporter.enabled
  name: elasticsearch-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.4.0
- condition: prometheus-elasticsearch-exporter.enabled
  name: elasticsearch-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.4.0df