apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nc-nginx-exporter
  namespace: nexclipper
  labels:
    app: nc-nginx-exporter
spec:
  selector:
    matchLabels:
      app: nc-nginx-exporter
  endpoints:
  - port: metrics
    interval: 30s