apiVersion: v1
appVersion: 0.1.3
description: A Helm chart for the Prometheus NGINX Exporter
home: https://github.com/nginxinc/nginx-prometheus-exporter
keywords:
- metrics
- nginx
- monitoring
maintainers:
- email: jinwoong@nexclipper.io
  name: jinwoong
name: nginx-exporter
version: 0.1.3
