apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-exporter.fullname" . }}
  labels:
    app: {{ template "nginx-exporter.name" . }}
    chart: {{ template "nginx-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "nginx-exporter.name" . }}
    release: {{ .Release.Name }}
